services:
  postgres:
    image: postgres:17
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=library_db
    container_name: postgres
